import type { TranscriptSegment } from '@/lib/analysis/types';

const FETCH_HEADERS = {
  'user-agent':
    'Mozilla/5.0 (compatible; ShortForge/0.3; +https://github.com/amineadd19-a11y/ShortForge)',
  'accept-language': 'en-US,en;q=0.9',
};

/**
 * Fetch official YouTube captions when the uploader enabled them.
 * Strategy:
 * 1) timedtext track list
 * 2) watch-page player caption tracks (more reliable from some hosts)
 * Never invents transcript text.
 */
export async function fetchYouTubeCaptions(videoId: string): Promise<TranscriptSegment[]> {
  if (!/^[a-zA-Z0-9_-]{6,20}$/.test(videoId)) return [];

  const fromTimedtext = await fetchViaTimedtext(videoId);
  if (fromTimedtext.length) return fromTimedtext;

  const fromPlayer = await fetchViaPlayerCaptions(videoId);
  return fromPlayer;
}

async function fetchViaTimedtext(videoId: string): Promise<TranscriptSegment[]> {
  try {
    const listUrl = `https://www.youtube.com/api/timedtext?type=list&v=${encodeURIComponent(videoId)}`;
    const listRes = await fetch(listUrl, {
      cache: 'no-store',
      headers: { ...FETCH_HEADERS, accept: 'application/xml,text/xml,*/*' },
      signal: AbortSignal.timeout(10_000),
    });
    if (!listRes.ok) return [];

    const listXml = await listRes.text();
    const tracks = [...listXml.matchAll(/<track[^>]*lang_code="([^"]+)"[^>]*(?:name="([^"]*)")?/g)].map(
      (m) => ({ lang: m[1], name: m[2] || '' }),
    );
    if (!tracks.length) return [];

    const preferred = pickTrack(tracks);
    const captionUrl = new URL('https://www.youtube.com/api/timedtext');
    captionUrl.searchParams.set('v', videoId);
    captionUrl.searchParams.set('lang', preferred.lang);
    captionUrl.searchParams.set('fmt', 'srv3');
    if (preferred.name) captionUrl.searchParams.set('name', preferred.name);

    const captionRes = await fetch(captionUrl.toString(), {
      cache: 'no-store',
      headers: { ...FETCH_HEADERS, accept: 'application/xml,text/xml,*/*' },
      signal: AbortSignal.timeout(12_000),
    });
    if (!captionRes.ok) return [];
    return parseCaptionXml(await captionRes.text());
  } catch {
    return [];
  }
}

async function fetchViaPlayerCaptions(videoId: string): Promise<TranscriptSegment[]> {
  try {
    const watchUrl = `https://www.youtube.com/watch?v=${encodeURIComponent(videoId)}&hl=en&gl=US`;
    const pageRes = await fetch(watchUrl, {
      cache: 'no-store',
      headers: {
        ...FETCH_HEADERS,
        accept: 'text/html,application/xhtml+xml',
      },
      signal: AbortSignal.timeout(12_000),
    });
    if (!pageRes.ok) return [];
    const html = await pageRes.text();

    const captionTracks = extractCaptionTracks(html);
    if (!captionTracks.length) return [];

    const preferred =
      captionTracks.find((t) => t.lang.startsWith('en') && !t.autoGenerated) ||
      captionTracks.find((t) => t.lang.startsWith('en')) ||
      captionTracks.find((t) => !t.autoGenerated) ||
      captionTracks[0];

    if (!preferred.baseUrl.startsWith('https://')) return [];

    const captionRes = await fetch(preferred.baseUrl, {
      cache: 'no-store',
      headers: { ...FETCH_HEADERS, accept: 'application/xml,text/xml,*/*' },
      signal: AbortSignal.timeout(12_000),
    });
    if (!captionRes.ok) return [];
    return parseCaptionXml(await captionRes.text());
  } catch {
    return [];
  }
}

function pickTrack(tracks: Array<{ lang: string; name: string }>) {
  return (
    tracks.find((t) => t.lang === 'en') ||
    tracks.find((t) => t.lang.startsWith('en')) ||
    tracks.find((t) => t.lang === 'fr') ||
    tracks.find((t) => t.lang === 'ar') ||
    tracks[0]
  );
}

function extractCaptionTracks(html: string): Array<{ lang: string; baseUrl: string; autoGenerated: boolean }> {
  const match = html.match(/ytInitialPlayerResponse\s*=\s*(\{.+?\});/s);
  if (!match) return [];
  try {
    const player = JSON.parse(match[1]) as {
      captions?: {
        playerCaptionsTracklistRenderer?: {
          captionTracks?: Array<{
            languageCode?: string;
            baseUrl?: string;
            kind?: string;
          }>;
        };
      };
    };
    const tracks = player.captions?.playerCaptionsTracklistRenderer?.captionTracks ?? [];
    return tracks
      .filter((t) => typeof t.baseUrl === 'string' && typeof t.languageCode === 'string')
      .map((t) => ({
        lang: t.languageCode as string,
        baseUrl: t.baseUrl as string,
        autoGenerated: t.kind === 'asr',
      }));
  } catch {
    return [];
  }
}

function decodeEntities(text: string): string {
  return text
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n/g, ' ')
    .replace(/\s+/g, ' ')
    .trim();
}

export function parseCaptionXml(xml: string): TranscriptSegment[] {
  const segments: TranscriptSegment[] = [];
  const pTags = [...xml.matchAll(/<p[^>]*t="(\d+)"[^>]*(?:d="(\d+)")?[^>]*>([\s\S]*?)<\/p>/g)];

  for (const match of pTags) {
    const startMs = Number(match[1]);
    const durationMs = Number(match[2] || 2000);
    const inner = match[3]
      .replace(/<s[^>]*>/g, '')
      .replace(/<\/s>/g, ' ')
      .replace(/<[^>]+>/g, ' ');
    const text = decodeEntities(inner);
    if (!text) continue;
    segments.push({
      start: startMs / 1000,
      end: (startMs + Math.max(durationMs, 400)) / 1000,
      text,
    });
  }

  if (!segments.length) {
    for (const match of xml.matchAll(/<text start="([\d.]+)"[^>]*dur="([\d.]+)"[^>]*>([\s\S]*?)<\/text>/g)) {
      const text = decodeEntities(match[3]);
      if (!text) continue;
      const start = Number(match[1]);
      const dur = Number(match[2]);
      segments.push({ start, end: start + Math.max(dur, 0.4), text });
    }
  }

  return mergeCloseSegments(segments);
}

function mergeCloseSegments(segments: TranscriptSegment[]): TranscriptSegment[] {
  if (!segments.length) return [];
  const out: TranscriptSegment[] = [];
  let current = { ...segments[0] };
  for (let i = 1; i < segments.length; i += 1) {
    const next = segments[i];
    if (next.start - current.end < 0.35 && current.text.length < 140) {
      current = {
        start: current.start,
        end: next.end,
        text: `${current.text} ${next.text}`.replace(/\s+/g, ' ').trim(),
      };
    } else {
      out.push(current);
      current = { ...next };
    }
  }
  out.push(current);
  return out;
}
