import http from 'node:http';
import { randomUUID } from 'node:crypto';
import { spawn } from 'node:child_process';
import { mkdir, stat, unlink, writeFile } from 'node:fs/promises';
import { createReadStream } from 'node:fs';
import path from 'node:path';
import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import { transcribeWithWhisper } from './transcribe.mjs';
import { analyzeVerticalCrop } from './reframe.mjs';

const PORT=Number(process.env.PORT||8787),WORK_DIR=process.env.WORK_DIR||'/tmp/shortforge',MAX_BODY=64*1024,MAX_DURATION=180,jobs=new Map();
const bucket=process.env.S3_BUCKET?.trim();
const s3=bucket?new S3Client({region:process.env.S3_REGION||'auto',endpoint:process.env.S3_ENDPOINT||undefined,forcePathStyle:process.env.S3_FORCE_PATH_STYLE==='true',credentials:process.env.S3_ACCESS_KEY_ID?{accessKeyId:process.env.S3_ACCESS_KEY_ID,secretAccessKey:process.env.S3_SECRET_ACCESS_KEY||''}:undefined}):null;
function json(res,status,body){res.writeHead(status,{'content-type':'application/json','cache-control':'no-store'});res.end(JSON.stringify(body));}
async function readBody(req){let size=0,text='';for await(const c of req){size+=c.length;if(size>MAX_BODY)throw new Error('Request body too large.');text+=c;}return JSON.parse(text||'{}');}
function youtubeUrl(v){try{const u=new URL(v);return u.protocol==='https:'&&['youtube.com','www.youtube.com','youtu.be','m.youtube.com'].includes(u.hostname);}catch{return false;}}
function run(cmd,args){return new Promise((resolve,reject)=>{const p=spawn(cmd,args,{stdio:['ignore','pipe','pipe']});let err='';p.stderr.on('data',c=>{err+=c;if(err.length>6000)err=err.slice(-6000);});p.on('error',reject);p.on('close',code=>code===0?resolve():reject(new Error(`${cmd} failed (${code}): ${err.slice(-2500)}`)));});}
async function downloadSource(url,t){await run('yt-dlp',['--no-playlist','--format','bv*[height<=1080]+ba/b[height<=1080]','--merge-output-format','mp4','--output',t,url]);}
function assTime(s){s=Math.max(0,s);const h=Math.floor(s/3600),m=Math.floor(s%3600/60),sec=Math.floor(s%60),cs=Math.floor((s-Math.floor(s))*100);return `${h}:${String(m).padStart(2,'0')}:${String(sec).padStart(2,'0')}.${String(cs).padStart(2,'0')}`;}
function assEscape(v){return String(v??'').replace(/[{}\\]/g,'').replace(/\r?\n/g,' ').trim();}
function buildAss(words,offset,duration){if(!Array.isArray(words)||!words.length)return null;const events=[];for(const w of words){const a=Number(w.start)-offset,b=Number(w.end)-offset;if(!Number.isFinite(a)||!Number.isFinite(b)||b<=0||a>=duration)continue;const text=assEscape(w.text);if(!text)continue;events.push(`Dialogue: 0,${assTime(Math.max(0,a))},${assTime(Math.min(duration,b))},Default,,0,0,0,,${text}`);}return events.length?`[Script Info]\nScriptType: v4.00+\nPlayResX: 1080\nPlayResY: 1920\n[V4+ Styles]\nFormat: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding\nStyle: Default,Arial,58,&H00FFFFFF,&H00FFFFFF,&H00000000,&H99000000,-1,0,0,0,100,100,0,0,1,4,1,2,70,70,300,1\n[Events]\nFormat: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text\n${events.join('\n')}\n`:null;}
async function render(job,input,output,captions,crop){const start=Math.max(0,Number(job.plan?.start??0)),end=Number(job.plan?.end);if(!Number.isFinite(end)||end<=start||end-start>MAX_DURATION)throw new Error('Invalid render duration.');const duration=end-start;const filters=[crop?.mode==='center'?'crop=ih*9/16:ih:(iw-ih*9/16)/2:0':'crop=ih*9/16:ih:(iw-ih*9/16)/2:0','scale=1080:1920:force_original_aspect_ratio=decrease','pad=1080:1920:(ow-iw)/2:(oh-ih)/2','setsar=1'];let assFile=null;const ass=buildAss(captions?.words,start,duration);if(ass){assFile=path.join(WORK_DIR,`${job.id}.ass`);await writeFile(assFile,ass,'utf8');filters.push(`subtitles=${assFile.replace(/\\/g,'/')}`);}try{await run('ffmpeg',['-ss',String(start),'-i',input,'-t',String(duration),'-vf',filters.join(','),'-map','0:v:0','-map','0:a?','-r','30','-c:v','libx264','-preset','veryfast','-crf','20','-c:a','aac','-movflags','+faststart','-y',output]);}finally{if(assFile)await unlink(assFile).catch(()=>{});}}
async function upload(file,key){if(!s3||!bucket)throw new Error('Object storage is not configured.');const size=(await stat(file)).size;await s3.send(new PutObjectCommand({Bucket:bucket,Key:key,Body:createReadStream(file),ContentType:'video/mp4',ContentLength:size,CacheControl:'private, max-age=3600'}));return getSignedUrl(s3,new GetObjectCommand({Bucket:bucket,Key:key}),{expiresIn:3600});}
async function processJob(job){job.status='processing';const template=path.join(WORK_DIR,`${job.id}-input.%(ext)s`),input=path.join(WORK_DIR,`${job.id}-input.mp4`),output=path.join(WORK_DIR,`${job.id}.mp4`);try{await downloadSource(job.sourceUrl,template);job.transcriptStatus='processing';const captions=await transcribeWithWhisper(input);job.transcriptStatus='ready';job.captions=captions;job.cropStatus='processing';const crop=await analyzeVerticalCrop(input,job.plan?.start||0,Math.min(MAX_DURATION,(job.plan?.end||0)-(job.plan?.start||0)));job.cropStatus='ready';job.crop=crop;await render(job,input,output,captions,crop);job.outputUrl=await upload(output,`shorts/${job.id}.mp4`);job.status='completed';}catch(e){job.status='failed';job.error=e instanceof Error?e.message:'Render failed.';}finally{await unlink(input).catch(()=>{});await unlink(output).catch(()=>{});}}
const server=http.createServer(async(req,res)=>{try{const u=new URL(req.url||'/',`http://${req.headers.host||'localhost'}`);if(req.method==='GET'&&u.pathname==='/healthz')return json(res,200,{ok:true,service:'shortforge-render-worker',version:'0.4.0'});if(req.method==='GET'&&u.pathname==='/readyz')return json(res,s3&&bucket?200:503,{ready:Boolean(s3&&bucket),storage:Boolean(s3&&bucket),transcription:true,render:true,reframe:true});if(req.method==='POST'&&u.pathname==='/jobs'){const x=await readBody(req);if(!youtubeUrl(x.sourceUrl))return json(res,400,{error:'A valid YouTube HTTPS URL is required.'});if(!s3||!bucket)return json(res,503,{error:'Worker object storage is not configured.'});const id=randomUUID(),job={id,sourceUrl:x.sourceUrl,plan:x.plan,captions:x.captions,status:'queued',transcriptStatus:'queued',cropStatus:'queued'};jobs.set(id,job);void processJob(job);return json(res,202,{jobId:id,status:'queued'});}const m=u.pathname.match(/^\/jobs\/([^/]+)$/);if(req.method==='GET'&&m){const j=jobs.get(m[1]);if(!j)return json(res,404,{error:'Job not found.'});return json(res,200,{jobId:j.id,status:j.status,transcriptStatus:j.transcriptStatus,cropStatus:j.cropStatus,outputUrl:j.outputUrl,error:j.error});}json(res,404,{error:'Not found.'});}catch(e){json(res,400,{error:e instanceof Error?e.message:'Invalid request.'});}});await mkdir(WORK_DIR,{recursive:true});server.listen(PORT,()=>console.log(`ShortForge render worker listening on ${PORT}`));
